import type { FeatureCollection, LineString, Point } from "geojson";

import corrections from "../data/corrections.json";
import generatedLocations from "../data/locations.json";
import stopsData from "../data/stops.json";
import { bookPlaceByName } from "./book";
import { formatPages } from "./format";
import type { Visits } from "./progress";

export interface Stop {
  /** Global narrative position across the whole journey, 1-based. */
  ordinal: number;
  /** indexName of the Place. */
  place: string;
  chapter: number;
  section: number;
  role: "stop" | "passed-through";
  latitude: number;
  longitude: number;
}

export interface TownLocation {
  name: string;
  latitude: number;
  longitude: number;
}

export interface TownProperties {
  /** Exact toponymic-index entry — the key used for progress tracking. */
  indexName: string;
  name: string;
  /** Page of the town's first appearance in the book (narrative order). */
  firstPage: number | null;
  /** Human-readable page references, e.g. "72, 98, 100". */
  pagesLabel: string | null;
  mentions: number;
  visited: boolean;
  /** ISO date of the visit, when known. */
  visitedDate: string | null;
  /** Zoom-disclosure tier (mapStyle.ts): 0 anchor Stop / visited, 1 Stop,
   * 2 passed-through, 3 referenced-only. */
  tier: 0 | 1 | 2 | 3;
  /** Chapter of the Place's first Stop; null for referenced-only places.
   * Drives chapter-focus dimming. */
  chapter: number | null;
}

// Overridable so a dev box or CI whose network can't reach the tile host can
// point the app at a mirror (EXPO_PUBLIC_MAP_STYLE_URL=http://localhost:9876/…).
export const MAP_STYLE_URL =
  process.env.EXPO_PUBLIC_MAP_STYLE_URL ||
  "https://tiles.openfreemap.org/styles/liberty";
export const MAP_CENTER: [number, number] = [-8.075, 39.414]; // [lon, lat]
export const INITIAL_ZOOM = 6;

/** Frame the whole country (the subject), not the Iberian centroid — the
 * initial camera fits these bounds with chrome-aware padding. */
export const PORTUGAL_BOUNDS: [[number, number], [number, number]] = [
  [-9.65, 36.85],
  [-6.1, 42.25],
];

// locations.json is generated by tools/map-generator; towns it could not
// geocode are stored as (0, 0). corrections.json holds manual fixes that
// take precedence over the generated entries.
const byName = new Map<string, TownLocation>();
for (const town of generatedLocations as TownLocation[]) byName.set(town.name, town);
for (const town of corrections as TownLocation[]) byName.set(town.name, town);

const hasCoordinates = (town: TownLocation) => town.latitude !== 0 || town.longitude !== 0;

export const towns: TownLocation[] = [...byName.values()].filter(hasCoordinates);

export const stops: Stop[] = stopsData.stops as Stop[];
export const TOTAL_STOPS = stops.length;

/**
 * Selectable Places in journey order, powering the detail panel's prev/next
 * stepper: the Stops in narrative order first (deduped — a Place can be hit by
 * several Stops), then any remaining clickable Place ordered by its first page
 * of appearance. Built from the same `towns` set useSelection treats as
 * selectable, so every entry has a marker to fly to.
 */
export const orderedPlaces: string[] = (() => {
  const selectable = new Set(towns.map((town) => town.name));
  const seen = new Set<string>();
  const order: string[] = [];
  for (const stop of stops) {
    if (selectable.has(stop.place) && !seen.has(stop.place)) {
      seen.add(stop.place);
      order.push(stop.place);
    }
  }
  const firstPage = (name: string) =>
    bookPlaceByName.get(name)?.pages[0] ?? Number.POSITIVE_INFINITY;
  const rest = towns
    .map((town) => town.name)
    .filter((name) => !seen.has(name))
    .sort((a, b) => firstPage(a) - firstPage(b));
  return [...order, ...rest];
})();

const placeOrderIndex = new Map(orderedPlaces.map((name, i) => [name, i]));

/** The adjacent selectable Place in journey order, or null at the ends. */
export function adjacentPlace(indexName: string, delta: 1 | -1): string | null {
  const index = placeOrderIndex.get(indexName);
  if (index === undefined) return null;
  return orderedPlaces[index + delta] ?? null;
}

/**
 * Multi-referent index entries ("Ermida" is a chapel noun, "São Vicente"
 * names four different churches/capes) carry per-chapter coordinates in
 * stops.json that differ from the Place's single global coordinate. Those
 * places render one dot per journey referent, at the route's coordinates,
 * instead of one orphan dot off the route.
 */
const movedStopsByPlace = new Map<string, Stop[]>();
for (const stop of stops) {
  const home = byName.get(stop.place);
  if (!home) continue;
  const moved =
    Math.abs(home.latitude - stop.latitude) > 1e-4 ||
    Math.abs(home.longitude - stop.longitude) > 1e-4;
  if (moved) {
    const list = movedStopsByPlace.get(stop.place) ?? [];
    list.push(stop);
    movedStopsByPlace.set(stop.place, list);
  }
}

const fullyMovedPlaces = new Set(
  [...movedStopsByPlace.keys()].filter((place) =>
    stops
      .filter((s) => s.place === place)
      .every((s) => movedStopsByPlace.get(place)!.includes(s)),
  ),
);

/**
 * The coordinate(s) a Place renders at — the single source of truth for both
 * its marker(s) and the point a selection flies to. A fully-moved multi-referent
 * Place renders one dot per journey referent at the route's coordinates; every
 * other Place renders one dot at its home coordinate. buildTownsGeoJson maps
 * over all of them and placeCenter takes the first, so the rendered marker and
 * the fly-to target can never drift apart. Empty only for a Place with no
 * coordinates (never the case for a member of `towns`).
 */
export function placeDots(indexName: string): [number, number][] {
  if (fullyMovedPlaces.has(indexName)) {
    return movedStopsByPlace
      .get(indexName)!
      .map((s) => [s.longitude, s.latitude] as [number, number]);
  }
  const home = byName.get(indexName);
  return home ? [[home.longitude, home.latitude]] : [];
}

// A Place's role on the journey, for disclosure tiers: "stop" wins over
// "passed-through"; a Place with no Stop at all is referenced-only.
const journeyRole = new Map<string, "stop" | "passed-through">();
const firstChapter = new Map<string, number>();
for (const stop of stops) {
  if (stop.role === "stop" || !journeyRole.has(stop.place)) {
    journeyRole.set(stop.place, stop.role);
  }
  if (!firstChapter.has(stop.place)) firstChapter.set(stop.place, stop.chapter);
}

/** Disclosure tier (TOWN_RADIUS/TOWN_OPACITY in mapStyle.ts). Anchor Stops —
 * the ones the book dwells on for 3+ pages — draw the journey at country
 * zoom; a Traveler's visited places always show (it is their journey). */
function dotTier(role: "stop" | "passed-through" | undefined, mentions: number, visited: boolean): 0 | 1 | 2 | 3 {
  if (visited) return 0;
  if (role === "stop") return mentions >= 3 ? 0 : 1;
  if (role === "passed-through") return 2;
  return 3;
}

export function buildTownsGeoJson(
  visits: Visits = new Map(),
): FeatureCollection<Point, TownProperties> {
  return {
    type: "FeatureCollection",
    features: towns.flatMap((town) => {
      const place = bookPlaceByName.get(town.name);
      const mentions = place?.pages.length ?? 0;
      const visited = visits.has(town.name);
      const properties = {
        indexName: town.name,
        name: place?.name ?? town.name,
        firstPage: place?.pages[0] ?? null,
        pagesLabel: place ? formatPages(place.pages) : null,
        mentions,
        visited,
        visitedDate: visits.get(town.name) ?? null,
        tier: dotTier(journeyRole.get(town.name), mentions, visited),
        chapter: firstChapter.get(town.name) ?? null,
      };
      return placeDots(town.name).map((coordinates) => ({
        type: "Feature" as const,
        geometry: { type: "Point" as const, coordinates },
        properties,
      }));
    }),
  };
}

export const townsGeoJson = buildTownsGeoJson();

/**
 * Where to recentre the map when a Place is selected (map click, search, a
 * shared deep link, or browser back/forward): the first of the Place's
 * rendered dots, so the camera always lands on a real marker. placeDots
 * explains why a fully-moved Place's home coordinate would be wrong — e.g.
 * "Torre (serra da Estrela)", whose only dot is the Torre de Belém stop in
 * Lisbon; centring on the home coordinate would fly to the summit instead.
 */
export function placeCenter(indexName: string): [number, number] | undefined {
  return placeDots(indexName)[0];
}

/**
 * The six chapter Routes (ADR 0003), as one segment per consecutive Stop
 * pair. Per-segment features let the timeline draw the journey
 * progressively with a GPU filter on `ordinal` (the segment's later Stop).
 */
export const routesGeoJson: FeatureCollection<
  LineString,
  { chapter: number; ordinal: number }
> = {
  type: "FeatureCollection",
  features: stops.flatMap((stop, i) => {
    const prev = stops[i - 1];
    if (!prev || prev.chapter !== stop.chapter) return [];
    return [
      {
        type: "Feature" as const,
        geometry: {
          type: "LineString" as const,
          coordinates: [
            [prev.longitude, prev.latitude],
            [stop.longitude, stop.latitude],
          ],
        },
        properties: { chapter: stop.chapter, ordinal: stop.ordinal },
      },
    ];
  }),
};
