import type { FeatureCollection, LineString, Point } from "geojson";

import corrections from "../data/corrections.json";
import generatedLocations from "../data/locations.json";
import stopsData from "../data/stops.json";
import { bookPlaceByName } from "./book";
import type { Visits } from "./progress";

export interface Stop {
  /** Global narrative position across the whole journey, 1-based. */
  ordinal: number;
  /** indexName of the Place. */
  place: string;
  chapter: number;
  section: number;
  role: "stop" | "passed-through";
  latitude: number;
  longitude: number;
}

export interface TownLocation {
  name: string;
  latitude: number;
  longitude: number;
}

export interface TownProperties {
  /** Exact toponymic-index entry — the key used for progress tracking. */
  indexName: string;
  name: string;
  /** Page of the town's first appearance in the book (narrative order). */
  firstPage: number | null;
  /** Human-readable page references, e.g. "72, 98, 100". */
  pagesLabel: string | null;
  mentions: number;
  visited: boolean;
  /** ISO date of the visit, when known. */
  visitedDate: string | null;
}

export const MAP_STYLE_URL = "https://tiles.openfreemap.org/styles/liberty";
export const MAP_CENTER: [number, number] = [-8.075, 39.414]; // [lon, lat]
export const INITIAL_ZOOM = 6;

// locations.json is generated by tools/map-generator; towns it could not
// geocode are stored as (0, 0). corrections.json holds manual fixes that
// take precedence over the generated entries.
const byName = new Map<string, TownLocation>();
for (const town of generatedLocations as TownLocation[]) byName.set(town.name, town);
for (const town of corrections as TownLocation[]) byName.set(town.name, town);

const hasCoordinates = (town: TownLocation) => town.latitude !== 0 || town.longitude !== 0;

export const towns: TownLocation[] = [...byName.values()].filter(hasCoordinates);

export const stops: Stop[] = stopsData.stops as Stop[];
export const TOTAL_STOPS = stops.length;

/**
 * Multi-referent index entries ("Ermida" is a chapel noun, "São Vicente"
 * names four different churches/capes) carry per-chapter coordinates in
 * stops.json that differ from the Place's single global coordinate. Those
 * places render one dot per journey referent, at the route's coordinates,
 * instead of one orphan dot off the route.
 */
const movedStopsByPlace = new Map<string, Stop[]>();
for (const stop of stops) {
  const home = byName.get(stop.place);
  if (!home) continue;
  const moved =
    Math.abs(home.latitude - stop.latitude) > 1e-4 ||
    Math.abs(home.longitude - stop.longitude) > 1e-4;
  if (moved) {
    const list = movedStopsByPlace.get(stop.place) ?? [];
    list.push(stop);
    movedStopsByPlace.set(stop.place, list);
  }
}

const fullyMovedPlaces = new Set(
  [...movedStopsByPlace.keys()].filter((place) =>
    stops
      .filter((s) => s.place === place)
      .every((s) => movedStopsByPlace.get(place)!.includes(s)),
  ),
);

export function buildTownsGeoJson(
  visits: Visits = new Map(),
): FeatureCollection<Point, TownProperties> {
  return {
    type: "FeatureCollection",
    features: towns.flatMap((town) => {
      const place = bookPlaceByName.get(town.name);
      const properties = {
        indexName: town.name,
        name: place?.name ?? town.name,
        firstPage: place?.pages[0] ?? null,
        pagesLabel: place?.pages.join(", ") ?? null,
        mentions: place?.pages.length ?? 0,
        visited: visits.has(town.name),
        visitedDate: visits.get(town.name) ?? null,
      };
      const dots = fullyMovedPlaces.has(town.name)
        ? movedStopsByPlace
            .get(town.name)!
            .map((s) => [s.longitude, s.latitude] as [number, number])
        : [[town.longitude, town.latitude] as [number, number]];
      return dots.map((coordinates) => ({
        type: "Feature" as const,
        geometry: { type: "Point" as const, coordinates },
        properties,
      }));
    }),
  };
}

export const townsGeoJson = buildTownsGeoJson();

/**
 * Where to recentre the map when a Place is selected (map click, search, a
 * shared deep link, or browser back/forward). It must match the Place's
 * *rendered* marker: a fully-moved place renders at its route's moved-stop
 * coordinates, not at the Place's stale home coordinate — e.g. "Torre (serra
 * da Estrela)", whose only dot is the Torre de Belém stop in Lisbon. Centring
 * on the home coordinate would fly to the Serra da Estrela summit instead.
 */
export function placeCenter(indexName: string): [number, number] | undefined {
  const moved = fullyMovedPlaces.has(indexName)
    ? movedStopsByPlace.get(indexName)?.[0]
    : undefined;
  if (moved) return [moved.longitude, moved.latitude];
  const home = byName.get(indexName);
  return home ? [home.longitude, home.latitude] : undefined;
}

/**
 * The six chapter Routes (ADR 0003), as one segment per consecutive Stop
 * pair. Per-segment features let the timeline draw the journey
 * progressively with a GPU filter on `ordinal` (the segment's later Stop).
 */
export const routesGeoJson: FeatureCollection<
  LineString,
  { chapter: number; ordinal: number }
> = {
  type: "FeatureCollection",
  features: stops.flatMap((stop, i) => {
    const prev = stops[i - 1];
    if (!prev || prev.chapter !== stop.chapter) return [];
    return [
      {
        type: "Feature" as const,
        geometry: {
          type: "LineString" as const,
          coordinates: [
            [prev.longitude, prev.latitude],
            [stop.longitude, stop.latitude],
          ],
        },
        properties: { chapter: stop.chapter, ordinal: stop.ordinal },
      },
    ];
  }),
};
