import quotesData from "../data/quotes.json";

/**
 * One short, verbatim, attributed quote per Stop (ADR 0005). Generated by
 * tools/book-pipeline; every quote is exact-match verified against the book
 * text before it lands here.
 */
const quotes: Record<string, string> = quotesData;

export function quoteFor(place: string): string | undefined {
  return quotes[place];
}
